Feat: Customizing 404 page
ansys/ansys-sphinx-theme pull request #147
Opened 2022-11-08 16:43 UTC by Revathyvenugopal162

Customized 404 page.

2022-11-09 19:30 UTC, MaxJPRey commented on src/ansys_sphinx_theme/latex/__init__.py
> +    page_name : str
```suggestion
    project_name : str
```

2022-11-09 19:30 UTC, MaxJPRey commented on src/ansys_sphinx_theme/latex/__init__.py
> +    issue_page : str
```suggestion
    issue_page : str, optional
```

2022-11-09 19:32 UTC, MaxJPRey commented on src/ansys_sphinx_theme/latex/__init__.py
> +        Mail id for the not found page mail, default is pyansys.support@ansys.com.
```suggestion
        E-mail address to contact. The default value is "``pyansys.support@ansys.com"``.
```

2022-11-10 07:23 UTC, RobPasMue reviewed
See my suggestions above. I'd change the way ``generate_404`` is called (and its arguments)

2022-11-10 07:23 UTC, RobPasMue commented on src/ansys_sphinx_theme/__init__.py
> +from .latex import generate_404  # noqa: F401
```suggestion
from ansys_sphinx_theme.latex import generate_404  # noqa: F401
```
Though useful, I'd avoid whenever possible relative imports... Clarity prevails over "coding fast"

2022-11-10 07:23 UTC, RobPasMue commented on src/ansys_sphinx_theme/latex/404.html
> +</h1>Or try mail to <a href="mailto:{{mail_id}}">{{team_name}}</a>.
```suggestion
</h1>Or try sending a mail to <a href="mailto:{{mail_id}}">{{team_name}}</a>.
```

2022-11-10 07:23 UTC, RobPasMue commented on src/ansys_sphinx_theme/latex/404.html
> +<p>If neither of those options work, please create a Github issue ticket <a href="{{issue_page}}">{{project_name}}.</a></p>
```suggestion
<p>If neither of those options work, please create a Github issue ticket in <a href="{{issue_page}}">{{project_name}}.</a></p>
```

2022-11-10 07:23 UTC, RobPasMue commented on src/ansys_sphinx_theme/latex/__init__.py
> +):
The issues page should be automatically deduced from the project's name and org that it belongs to. I think the best input arguments should be: ``org`` or ``owner``, ``project_name``, ``mail_id`` and ``team_name``.

``issue_page`` can then be created as:

```py
def generate_404(
    owner="ansys",
    project_name="ansys-sphinx-theme",
    mail_id="pyansys.support@ansys.com",
    team_name="PyAnsys",
):
    issue_page = f"https://github.com/{owner}/{project_name}/issues"
```

2022-11-10 10:50 UTC, jorgepiloto requested changes

2022-11-10 10:50 UTC, jorgepiloto commented on doc/source/user_guide/404_page.rst
> +    'body': generate_404(<issue_page_of_project to direct>,
In line with what @RobPasMue said, remember to remove this argument in the documentation too, as it can be computed inside of the function.

2022-11-10 15:56 UTC, RobPasMue approved these changes

2022-11-10 17:34 UTC, MaxJPRey commented on src/ansys_sphinx_theme/latex/__init__.py
> +       Name of the team
```suggestion
       Name of the team.
```

2022-11-10 17:41 UTC, MaxJPRey approved these changes
Excellent improvement @Revathyvenugopal162 that will benefit all the teams.
Thanks for the thorough review  @RobPasMue and @jorgepiloto .

2022-11-11 07:11 UTC, merged

2022-11-11 07:11 UTC, RobPasMue commented
Merging since it's ready =)